name: Run API Security Tests

on:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make tests executable
        run: chmod +x tests.sh

      - name: Run security tests
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: ./tests.sh
